name: ADCP
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - tensorflow-gpu=2.10.0
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - xgboost=1.7.3
  - lightgbm=3.3.5
  - catboost=1.1.1
  - mapie=0.7.0
  - pip:
    - pillow==8.0.0
    - requests==2.25.0
    - torch==1.7.0
    - torchvision==0.8.0